### ISSUE TITLE
Is there an English version of react illustration series 

### ISSUE THREAD

**Issue by tmkasun** [7kms/react-illustration-series#10]
This looks like an interesting illustration series, But sadly I can't read this language (Chinees ? Japanese ?), Is there an English version of this explanation?

**Comment by 7kms** [comment]
This is a Chinese document. I'm sorry, there is no English version right now.

**Comment by tmkasun** [comment]
ok Thank you

**Comment by jgchenu** [comment]
这是我的微信cjg_5288，想请问下是否有意向做英文版，我可以参与翻译，已经阅读完大部分的源码跟您的文章，如果方便的话请您联系我好吗，我这边尝试给您发过两次邮件，不过貌似没收到回复～

**Comment by 7kms** [comment]
> 这是我的微信cjg_5288，想请问下是否有意向做英文版，我可以参与翻译，已经阅读完大部分的源码跟您的文章，如果方便的话请您联系我好吗，我这边尝试给您发过两次邮件，不过貌似没收到回复～

做英文版有点犹豫,  因为现在图解部分就只有fiber构造算是详解,  其他部分基本上没什么图(主要是感觉不用配图, 强行配图会比较突兀).  

所以我觉得有特色的就是fiber构造部分.  最多也就是针对这一部分翻译一下?  其他感觉部分必要性不大
