### ISSUE TITLE
移动端页面有问题，无法导航

### ISSUE THREAD

**Issue by jaluik** [7kms/react-illustration-series#112]
在手机端，导航等功能点击无效果，无法导航

ps: 之前的框架好好的呀，现在dumi移动端适配有问题

![image](https://github.com/7kms/react-illustration-series/assets/37829041/de275703-f96d-4aa2-b318-9ffb05c6572c)

![image](https://github.com/7kms/react-illustration-series/assets/37829041/67684572-cc19-40a7-9e0e-5eca5f24cd34)

**Comment by jaluik** [comment]
我测试了一下，应该是google ads 脚本和dumi 冲突造成的问题

**Comment by 7kms** [comment]
好的，谢谢指正。 我看怎么改一下，不行就把ad去掉
