### ISSUE TITLE
流程图工具

### ISSUE THREAD

**Issue by wooter-s** [7kms/react-illustration-series#3]
写的真好！请问流程图用什么工具画的 @7kms

**Comment by wooter-s** [comment]
写的真好！请问流程图用什么工具画的 @7kms

**Comment by 7kms** [comment]
> 写的真好！请问流程图用什么工具画的 @7kms

https://www.omnigroup.com/omnigraffle/

**Comment by wooter-s** [comment]
> > 写的真好！请问流程图用什么工具画的 @7kms
> 
> 
> 
> https://www.omnigroup.com/omnigraffle/

谢谢
