### ISSUE TITLE
Question: why ignore `package-lock.json` and `yarn.lock` file?

### ISSUE THREAD

**Issue by sabertazimi** [7kms/react-illustration-series#30]
想问下聚聚为啥把 lockfile 加入 `.gitignore`，是出于何种考量？

**Comment by sabertazimi** [comment]
我提了一个 #31 GitHub Pages 构建的 PR。没有 lockfile 的话，无法开启 [actions/setup-node](https://github.com/actions/setup-node) 的 `cache: 'npm'` 选项，构建速度会受一点小小的影响。

当然如果聚聚不想在这个仓库下构建在线文档的话，直接把 #30 #31 同时关掉就行。

**Comment by 7kms** [comment]
好的哈,  我处理一下这个问题.
