### ISSUE TITLE
赞！感谢分享！（顺便有个小建议

### ISSUE THREAD

**Issue by Thoxvi** [7kms/react-illustration-series#35]
[这行](https://github.com/7kms/react-illustration-series/blame/master/docs/algorithm/bitfiled.md#L199) 多了个 `-`

还有请问一下现在有计划加入排版规范吗？比如[这种](https://github.com/sparanoid/chinese-copywriting-guidelines)？

**Comment by 7kms** [comment]
可以加呀,  有没有什么自动化的工具可以修正中文半角的呀.

文档里面很多使用了半角符号,  严格来讲中文标点应该使用全角.

**Comment by Thoxvi** [comment]
> 可以加呀, 有没有什么自动化的工具可以修正中文半角的呀.
> 
> 文档里面很多使用了半角符号, 严格来讲中文标点应该使用全角.

这里有些[工具](https://github.com/sparanoid/chinese-copywriting-guidelines#%E5%B7%A5%E5%85%B7)，可以看看能不能加到 GitHub Action 里面

**Comment by Thoxvi** [comment]
我刚刚用 pangu 搓了一个小脚本来修复这个问题，等会我提个 PR 你看看？

**Comment by 7kms** [comment]
> 我刚刚用 [pangu](https://github.com/vinta/pangu.js) 搓了一个小脚本来修复这个问题，等会我提个 PR 你看看？后续可以把这个检查加到 GitHub Action 里面，如果不通过就挂 CI

好的哈

**Comment by Thoxvi** [comment]
#36 可以看看，不过毕竟是脚本替换的，所以有些小问题在里面（不过总的来说比原来能看一些）
