### ISSUE TITLE
可否搞个交流群，大家一起对照着问题看源码效果更好些

### ISSUE THREAD

**Issue by honpery** [7kms/react-illustration-series#5]

**Comment by 7kms** [comment]
好的亲,  确实需要一个群交流更方便.

**Comment by 7kms** [comment]
<img src="https://user-images.githubusercontent.com/12625342/103300692-6d76e880-4a3a-11eb-99f5-bcdd41279e64.jpg" width="200px">

那就先建一个微信群吧, 一起探讨源码

**Comment by XuHatcher** [comment]
> <img alt="" width="240px" src="https://user-images.githubusercontent.com/12625342/104807354-6d882e00-5819-11eb-90eb-810d24554829.png">
> 
> 那就先建一个微信群吧, 一起探讨源码

二维码过期了啊

**Comment by jgchenu** [comment]
二维码过期了～可以麻烦更新一下吗，这是我的微信cjg_5288，想请问下是否有意向做英文版，我可以参与翻译，已经阅读完大部分的源码跟您的文章

**Comment by singagain** [comment]
劳烦更新一下二维码～

**Comment by lmxyjy** [comment]
二维码过期了，捞一下
