### ISSUE TITLE
关于hook update对象的问题

### ISSUE THREAD

**Issue by lmxyjy** [7kms/react-illustration-series#51]
在[React 应用中的高频对象](https://github.com/7kms/react-illustration-series/blob/master/docs/main/object-structure.md)一文中。
![image](https://user-images.githubusercontent.com/48620706/140453218-b316903d-1d44-48ac-8471-b792ecc61990.png)

对于`hook`对象的介绍中。并没有对其`update`和`updateQueue`对象的属性进行解释说明。是不是可以加上呢？

**Comment by 7kms** [comment]
这个其实是属于Hook原理部分的内容, 再加上一点链表的知识.   
这一章高频对象的介绍,  只是提前了解一下Hook数据结构, 后续章节都有详细介绍, 写太多了跑题.

后面v18版本还会对这一节进行修订, 或许不要这一节了.
