### ISSUE TITLE
runWithPriority 异步疑惑？

### ISSUE THREAD

**Issue by creamidea** [7kms/react-illustration-series#71]
<img width="651" alt="image" src="https://user-images.githubusercontent.com/1274730/157590036-08f23666-f19c-4394-a921-b91729aa8bf7.png">

在 17.0.2 中，runWithPriority 查看其[实现](https://github.com/facebook/react/blob/e0aa5e205feee53043ce1ae8726fe732866e6ea7/packages/react-reconciler/src/ReactEventPriorities.new.js#L39)已经是同步。这部分有点疑惑，不知道 @7kms 是怎么理解？

**Comment by 7kms** [comment]
不要疑惑哈,  这里确实是写错了哈,  `runWithPriority`这个函数本身是同步调用的. 

它设置了当前的调度优先级为`priorityLevel`, 如果在`flushPassiveEffectsImpl`中处理`effect`时又发起了新的更新, 那么新的`update.lane`将会受到这个`priorityLevel`影响.

**Comment by creamidea** [comment]
感谢，解释的非常的好。
