### ISSUE TITLE
effect hooks图例的构造顺序是否有问题

### ISSUE THREAD

**Issue by Jinminrui** [7kms/react-illustration-series#95]
大佬你好，在下面这篇文章中
https://github.com/7kms/react-illustration-series/blob/main/docs/main/hook-effect.md
![image](https://user-images.githubusercontent.com/24985290/190338870-3865a64e-1552-4dd7-b056-7f8fffb1fbc6.png)
从下面这张图里看 hooks 的书写顺序应该是 1 ，2 ，3
![image](https://user-images.githubusercontent.com/24985290/190336828-8040326e-b38b-457e-88a8-15194728f95a.png)
而 componentUpdateQueue.lastEffect 指向的应该是最后一个effect
![image](https://user-images.githubusercontent.com/24985290/190337097-fa82bd39-061c-4d99-9b92-be7d745e82bc.png)
所以这里不是很明白。

**Comment by Chastrlove** [comment]
你是对的

**Comment by 7kms** [comment]
是的哈，谢谢指正，连线确实错误。 
`fiber.updateQueue.lastEffect`指向的是最新的`effect`。 图上来讲的话，应该指向链表中的最后一个
